services:
  dev:
    image: mcr.microsoft.com/devcontainers/dotnet:9.0
    command: sleep infinity
    volumes:
      - ../../samples/dotnet:/workspace
    environment:
      - SQL_CREDENTIAL=Server=sql,1433;User Id=sa;Password=P@ssw.rd;TrustServerCertificate=True;Encrypt=True;
    depends_on:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw.rd
    expose:
      - 1433